# Generated by Django 3.2.8 on 2021-11-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuessCategory',
            fields=[
                ('cat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'guess_category',
            },
        ),
        migrations.CreateModel(
            name='LocationCategory',
            fields=[
                ('cat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('scname', models.CharField(max_length=255)),
                ('exclude', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'location_category',
            },
        ),
        migrations.CreateModel(
            name='SeedClientSetting',
            fields=[
                ('seedclient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('clienttype', models.CharField(choices=[('qb', 'qbittorrent'), ('tr', 'transmission'), ('de', 'deluge')], default='qb', max_length=2, verbose_name='类型')),
                ('host', models.CharField(max_length=128, verbose_name='主机地址')),
                ('port', models.IntegerField(default=8080, verbose_name='端口')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('online', models.IntegerField(choices=[(0, 'unknown'), (1, 'failed'), (2, 'loading'), (3, 'online'), (4, 'loaded'), (5, 'connecting')], default=0, verbose_name='连接状态')),
                ('num_total', models.BigIntegerField(default=0, verbose_name='种子数')),
                ('size_total', models.BigIntegerField(default=0, verbose_name='种子总大小')),
                ('num_active', models.BigIntegerField(default=0, verbose_name='活跃种子数')),
                ('num_downloading', models.BigIntegerField(default=0, verbose_name='正在下载')),
                ('root_dir', models.CharField(default='', max_length=255, verbose_name='存储根目录')),
            ],
            options={
                'db_table': 'seed_client',
            },
        ),
        migrations.CreateModel(
            name='TrackerCategory',
            fields=[
                ('cat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tracker', models.CharField(max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tracker_category',
            },
        ),
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('torrent_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('location', models.CharField(max_length=255)),
                ('hash', models.CharField(default='', max_length=255)),
                ('tracker', models.CharField(max_length=128)),
                ('addedDate', models.DateTimeField(blank=True, default=0)),
                ('origin_category', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=32)),
                ('categorized', models.IntegerField(default=0)),
                ('guess_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seedclient.guesscategory')),
                ('location_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seedclient.locationcategory')),
                ('sclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seedclient.seedclientsetting')),
                ('tracker_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seedclient.trackercategory')),
            ],
            options={
                'db_table': 'torrent',
            },
        ),
        migrations.CreateModel(
            name='CategorizeStep',
            fields=[
                ('catstep_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('totalTorrentNum', models.IntegerField(default=0)),
                ('currentProceedingNum', models.IntegerField(default=0)),
                ('totalMovedNum', models.IntegerField(default=0)),
                ('location_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seedclient.locationcategory')),
                ('sclient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seedclient.seedclientsetting')),
            ],
        ),
    ]
