# Generated by Django 3.2.8 on 2021-11-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedclient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='groupname',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
