# Generated by Django 3.2.8 on 2021-11-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedclient', '0002_torrent_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='groupname',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
