# Generated by Django 3.2.9 on 2021-11-13 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seedclient', '0003_alter_torrent_groupname'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedPoint',
            fields=[
                ('speedpoint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('sum_upload_speed', models.FloatField(default=0)),
                ('sum_download_speed', models.FloatField(default=0)),
                ('sclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seedclient.seedclientsetting')),
            ],
        ),
        migrations.CreateModel(
            name='SpeedingTorrent',
            fields=[
                ('torrent_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('hash', models.CharField(default='', max_length=255)),
                ('tracker', models.CharField(max_length=128)),
                ('addedDate', models.DateTimeField(blank=True, default=0)),
                ('status', models.CharField(max_length=32)),
                ('last_uploaded', models.BigIntegerField(default=0)),
                ('delta_uploaded', models.BigIntegerField(default=0)),
                ('last_downloaded', models.BigIntegerField(default=0)),
                ('delta_downloaded', models.BigIntegerField(default=0)),
                ('cur_progress', models.FloatField(default=0)),
                ('ttl', models.IntegerField(default=0)),
                ('sclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seedclient.seedclientsetting')),
            ],
        ),
    ]
