# Generated by Django 3.2.9 on 2021-11-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedclient', '0006_auto_20211114_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorizestep',
            name='trackList',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
