# Generated by Django 3.2.8 on 2021-11-27 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seedclient', '0007_categorizestep_tracklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveList',
            fields=[
                ('movelist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('moveto_location', models.CharField(default='', max_length=255)),
                ('torrent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seedclient.torrent')),
            ],
        ),
    ]
