# Generated by Django 3.2.9 on 2021-11-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedclient', '0008_movelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesscategory',
            name='root_dir',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guesscategory',
            name='label',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guesscategory',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
